name: CI

on:
  push:
    branches:
      - main
      - first-lab
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install dependencies
        run: |
          opam install . --deps-only --with-test
          opam install ounit2
          opam exec -- dune build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Lint documentation
        uses: ocaml/setup-ocaml/lint-doc@v3

      - name: Lint formatting
        uses: ocaml/setup-ocaml/lint-fmt@v3

      - name: Lint opam
        uses: ocaml/setup-ocaml/lint-opam@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
            
      - name: Run tests
        run: opam exec -- dune runtest
        env:
          REPORT_PATH: ${{ github.workspace }}/_build/report.xml  
